### ISSUE TITLE
docs to gh-pages?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/BioProviders#3]
Are the docs published to gh-pages?

An example where we do this auto-magically on every push to main is here: https://github.com/fsprojects/FSharp.Data/blob/main/.github/workflows/push-master.yml#L25-L31

**Comment by AlexKenna** [comment]
Documentation is now being published auto-magically [here](https://fsprojects.github.io/BioProviders/). Thanks for the guidance @dsyme.
