### ISSUE TITLE
nuget package?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/BioProviders#4]
Consider auto-publishing a nuget off pushes to main?

For example like here: https://github.com/fsprojects/FSharp.Data/blob/main/.github/workflows/push-master.yml#L34-L35

**Comment by AlexKenna** [comment]
This has been implemented as of [this](https://github.com/fsprojects/BioProviders/tree/e311037ca647b6abb3de7bdec67109e592bbb97c) commit.
